{% set name = "prody" %}
{% set version = "2.6.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/prody/{{ name }}.git
  git_tag: v{{ version }}

build:
  number: 0
  entry_points:
    - prody = prody.apps:prody_main
    - evol = prody.apps:evol_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cross-python_{{ target_platform }}   # [build_platform != target_platform]
    - {{ stdlib("c") }}                    # [build_platform != target_platform]
    - pip

  host:
    - python
    - pip
    - setuptools
    - numpy >1.10
    - scipy
    - pyparsing <=3.1.1
    - biopython
    - requests

  run:
    - python
    - numpy >1.10
    - scipy
    - pyparsing <=3.1.1
    - biopython
    - requests

test:
  requires:
    - pytest
    - pytest-xprocess
  commands:
    - prody --help
    - evol --help
  imports:
    - prody
    - prody.atomic
    - prody.database
    - prody.dynamics
    - prody.ensemble
    - prody.kdtree.kdtree
    - prody.kdtree
    - prody.measure
    - prody.proteins
    - prody.sequence
    - prody.trajectory

about:
  home: http://www.bahargroup.org/prody/
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: ProDy is a free and open-source Python package for protein structure, dynamics, and sequence analysis, developed by the Bahar lab.
  doc_url: http://www.bahargroup.org/prody/manual/
  dev_url: https://github.com/prody/ProDy

extra:
  recipe-maintainers:
    - AnthonyBogetti
    - jamesmkrieger
    - simonbray
    - vbadwaj
