{% set name = "ProDy" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/prody/ProDy/archive/v{{ version }}.tar.gz
  sha256: b99597cd6655e9d3d3875f63c05f8ab0d9e6e25bbf48f248faa25a4d634d715e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - prody = prody.apps:prody_main
    - evol = prody.apps:evol_main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip <21.1
    - numpy >=1.10
  run:
    - python
    - biopython
    - matplotlib-base
    - pyparsing
    - requests
    - setuptools  # requires pkg_resources at runtime
    - scipy
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - prody --help
    - evol --help
  imports:
    - prody
    - prody.atomic
    - prody.database
    - prody.dynamics
    - prody.ensemble
    - prody.kdtree
    - prody.measure
    - prody.proteins
    - prody.sequence
    - prody.trajectory

about:
  home: http://www.bahargroup.org/prody/
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: ProDy is a free and open-source Python package for protein structure, dynamics, and sequence analysis, developed by the Bahar lab.
  description: |
    ProDy is a free and open-source Python package for protein 
    structure, dynamics, and sequence analysis, developed by the
    Bahar lab. It allows for comparative analysis and modeling of 
    protein structural  dynamics and sequence co-evolution. Fast 
    and flexible ProDy API is for interactive usage as well as 
    application development. ProDy also comes with several analysis 
    applications and a graphical user interface for visual analysis.
  doc_url: http://www.bahargroup.org/prody/manual/
  dev_url: https://github.com/prody/ProDy

extra:
  recipe-maintainers:
    - jamesmkrieger
    - simonbray
