name: Fork build (no upload)
on: [push, pull_request]

jobs:
  linux-64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [linux_64_python3.10, linux_64_python3.11, linux_64_python3.12]
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: build
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict
          create-args: >
            conda-build conda-forge-ci-setup boa python=3.12
      - name: Build
        shell: bash -l {0}
        env:
          CONFIG: ${{ matrix.config }}
          UPLOAD_PACKAGES: "False"
        run: |
          set -euxo pipefail
          setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
          source run_conda_forge_build_setup
          conda mambabuild recipe -m .ci_support/${CONFIG}.yaml --no-anaconda-upload

  osx-arm64:
    runs-on: macos-14   # Apple Silicon runner
    strategy:
      fail-fast: false
      matrix:
        config: [osx_arm64_python3.10, osx_arm64_python3.11, osx_arm64_python3.12]
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: build
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict
          create-args: >
            conda-build conda-forge-ci-setup boa python=3.12
      - name: Build
        shell: bash -l {0}
        env:
          CONFIG: ${{ matrix.config }}
          UPLOAD_PACKAGES: "False"
        run: |
          set -euxo pipefail
          setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
          source run_conda_forge_build_setup
          conda mambabuild recipe -m .ci_support/${CONFIG}.yaml --no-anaconda-upload
  osx-64:
    runs-on: macos-13     # Intel runner
    strategy:
      fail-fast: false
      matrix:
        config: [osx_64_python3.10, osx_64_python3.11, osx_64_python3.12]
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: build
          condarc: |
            channels:
              - conda-forge
            channel_priority: strict
          create-args: >
            conda-build conda-forge-ci-setup boa python=3.12
      - name: Build
        shell: bash -l {0}
        env:
          CONFIG: ${{ matrix.config }}
          UPLOAD_PACKAGES: "False"
        run: |
          set -euxo pipefail
          setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
          source run_conda_forge_build_setup
          conda mambabuild recipe -m .ci_support/${CONFIG}.yaml --no-anaconda-upload
