name: Fork CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [linux_64_python3.10, linux_64_python3.11, linux_64_python3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Build (Linux)
        env:
          CONFIG: ${{ matrix.config }}
          UPLOAD_PACKAGES: "False"
          CI: github_actions
        run: ./.scripts/run_docker_build.sh

  macos-x86_64:
    runs-on: macos-13     # Intel runner; keep if you want x86_64 wheels
    strategy:
      fail-fast: false
      matrix:
        config: [osx_64_python3.10, osx_64_python3.11, osx_64_python3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Build (macOS x86_64)
        env:
          CONFIG: ${{ matrix.config }}
          UPLOAD_PACKAGES: "False"
          CI: github_actions
        run: ./.scripts/run_osx_build.sh

  macos-arm64:
    runs-on: macos-latest  # Apple Silicon runner
    strategy:
      fail-fast: false
      matrix:
        config: [osx_arm64_python3.10, osx_arm64_python3.11, osx_arm64_python3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Build (macOS arm64)
        env:
          CONFIG: ${{ matrix.config }}
          UPLOAD_PACKAGES: "False"
          CI: github_actions
        run: ./.scripts/run_osx_build.sh
